### PR TITLE
Update cmakelists

### PR DESCRIPTION
**Pull request by steakhal**
## CMake related stuff, mostly refactorings

- Simplifies a lot of things using CMake generator expressions.
- Hardcodes the two `test` targets, testing the `c++17` and `c++20` standards.
- There is no guard on `c++17` tests since the library itself relies on `c++17`.

### CODE REVIEW

**Comment by Neargye** [comment]
Can I merge this?

**Comment by steakhal** [comment]
Not yet.

**Comment by steakhal** [comment]
Could you set the merging behavior in the settings to `Squash and merge`?

**Comment by Neargye** [comment]
Ok, no problem.

**Pull request merged**
